In [1]:
import numpy as np

In [75]:
def decomp_lu(A):
    assert len(A.shape) == 2, 'Deve ser uma matriz.'
    assert A.shape[0] == A.shape[1], 'A matriz deve ser quadrática.'
    
    n = A.shape[0]

    L = np.eye(n)
    U = np.zeros(A.shape)
    
    for i in range(n):
        for j in range(n):
            if i <= j:
                soma = 0
                for k in range(i):
                    soma += L[i,k] * U[k,j]
                U[i,j] = A[i,j] - soma
            else:
                soma = 0
                for k in range(j):
                    soma += L[i,k] * U[k,j]
                L[i,j] = (A[i,j] - soma) / U[j,j]
    return L, U

def gauss_simples(A, b):
    
    assert len(A.shape) == 2, 'Deve ser uma matriz.'
    assert A.shape[0] == A.shape[1], 'A matriz deve ser quadrática.'
    assert b.shape[0] == A.shape[0]
    
    n = A.shape[0]
    
    Ag = np.concatenate((A, b), axis=1)
    
    print(f'Initially: Ag=\n{Ag}\n')
        
    nsteps = n - 1
    for k in range(nsteps):
        for i in range(k+1,n):
            for j in range(k, n+1):
                print(Ag[i,j],Ag[k,j],Ag[i,k],Ag[k,k])
                Ag[i,j] = Ag[i,j] - Ag[k,j] * Ag[i,k] / Ag[k,k]
                print(k,i,j)
        print(f'Step {k} ->\n {Ag}\n')
        
    return Ag


In [69]:
A = np.array([ [6, 2, -1], [3, 4, 1], [3, 2, 8] ])
print(f'A={A}')

A=[[ 6  2 -1]
 [ 3  4  1]
 [ 3  2  8]]


In [70]:
L,U = decomp_lu(A)
print(f'L={L}')
print(f'U={U}')
print(L @ U)

L=[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
U=[[ 6.   2.  -1. ]
 [ 0.   3.   1.5]
 [ 0.   0.   8. ]]
[[ 6.  2. -1.]
 [ 3.  4.  1.]
 [ 3.  2.  8.]]


In [71]:
b = np.array([ [7], [7], [13] ])
b

array([[ 7],
       [ 7],
       [13]])

In [76]:
Ag = gauss_simples(A,b)
print(Ag)

Initially: Ag=
[[ 6  2 -1  7]
 [ 3  4  1  7]
 [ 3  2  8 13]]

3 6 3 6
0 1 0
4 2 0 6
0 1 1
1 -1 0 6
0 1 2
7 7 0 6
0 1 3
3 6 3 6
0 2 0
2 2 0 6
0 2 1
8 -1 0 6
0 2 2
13 7 0 6
0 2 3
Step 0 ->
 [[ 6  2 -1  7]
 [ 0  4  1  7]
 [ 0  2  8 13]]

2 4 2 4
1 2 1
8 1 0 4
1 2 2
13 7 0 4
1 2 3
Step 1 ->
 [[ 6  2 -1  7]
 [ 0  4  1  7]
 [ 0  0  8 13]]

[[ 6  2 -1  7]
 [ 0  4  1  7]
 [ 0  0  8 13]]
