In [1]:
import numpy as np

# inicialização das matrizes

In [ ]:
m = 5
n = 3
p = 4
A = np.random.rand(m,n)
print(f'A matriz criada é {A}\n')
print(f'O formato da matriz é {A.shape}\n')

In [ ]:
B = np.random.rand(n,p)
print(f'A matriz criada é {B}\n')
print(f'O formato da matriz é {B.shape}\n')

In [ ]:
C = np.random.rand(n,p)
print(f'A matriz criada é {C}\n')
print(f'O formato da matriz é {C.shape}\n')

# verificação das propriedades matriciais

In [ ]:
# propridedade distributiva
R1 = np.matmul(A, B)
R2 = np.matmul(A, C)
R3 = R1 + R2
print(f'O valor do resultado é {R3}\n')
print(f'O formato do resultado é {R3.shape}\n')
R4 = A @ (B + C)
print(f'O valor do resultado é {R4}\n')
print(f'O formato do resultado é {R4.shape}\n')

In [ ]:
# propriedade associativa
R1 = A @ (B @ C.T)
R2 = (A @ B) @ C.T
print(f'O valor do resultado é {R1}\n')
print(f'O formato do resultado é {R1.shape}\n')
print(f'O valor do resultado é {R2}\n')
print(f'O formato do resultado é {R2.shape}\n')

# trabalhando com vetores

In [ ]:
m = 5
n = 1
b = np.random.rand(m,n)
print(f'O vetor criado é {b}\n')
print(f'O formato do vetor é {b.shape}\n')
x = np.random.rand(m,n)
print(f'O vetor criado é {x}\n')
print(f'O formato do vetor é {x.shape}\n')
ProdInt = x.T @ b
print(f'o produto interno entre x e b é {ProdInt}\n')

# verificando a inversão de matrizes para a solução de sistemas lineares no formato $Ax=b$

In [ ]:
!pip install scipy

In [8]:
A = np.array([[5, 2, 1],[3, 1, 4], [1, 1, 3]])
print(f'A matriz de coeficientes é:\n {A}\n')
b = np.array([0, -7, -5])
print(f'A matriz de coeficientes é:\n {b}\n')
print(f'O formato de b é: {b.shape}\n')
b = np.reshape(b, (3,1))
print(f'O formato de b é: {b.shape}\n')

A matriz de coeficientes é:
 [[5 2 1]
 [3 1 4]
 [1 1 3]]

A matriz de coeficientes é:
 [ 0 -7 -5]

O formato de b é: (3,)

O formato de b é: (3, 1)



In [9]:
from scipy import linalg

In [10]:
# matriz inversa
A_inv = linalg.inv(A)
print(f'A inversa da matriz de coeficientes é:\n {A_inv}\n')
print(f'O formato de A_inv é: {A_inv.shape}\n')

A inversa da matriz de coeficientes é:
 [[ 0.07692308  0.38461538 -0.53846154]
 [ 0.38461538 -1.07692308  1.30769231]
 [-0.15384615  0.23076923  0.07692308]]

O formato de A_inv é: (3, 3)



In [12]:
# a solução será
x = A_inv @ b
print(f'A solução do sistema é\n {x}\n')
print(f'O formato de x é {x.shape}\n')


A solução do sistema é
 [[ 0.]
 [ 1.]
 [-2.]]

O formato de x é (3, 1)

