In [7]:
import numpy as np
from scipy import linalg

# Funçoes para a solução de sistemas lineares

In [23]:
def decomp_A(A):
    '''
    Decomposição A nas matrizes triangulares e diagonais.
    
    Entrada:
        A : matriz de coeficientes.
    Saída:
        L : matriz triangular inferior.
        D : matriz diagonal.
        R : matriz triangular superior.
    '''
    L = np.tril(A, k=-1)
    D = np.diag(np.diag(A))
    R = np.triu(A, k=1)
    return L, D, R

def metodo_jacobi_richardson(A,b,x0,epsilon,MAX_ITER):
    '''
    Resolver um sistema linear usando Jocobi-Richardson.
    
    Entrada:
        A : matriz de coeficientes.
        b : vetor de termos independentes.
        x0 : valor inicial de x.
        epsilon : tolerância máxima.
        MAX_ITER : número máximo de iterações.
    Saída:
        x : vetor de incógnitas
    '''
    assert len(A.shape) == 2, 'Dever ser uma matriz (2D).'
    assert A.shape[0] == A.shape[1], 'Dever ser uma matriz quadrada.'
    
    # ordem do sistema
    n = A.shape[0]
    
    # decomposição de A
    L,D,R = decomp_A(A)
    
    # normalização de L, R, b
    for i in range(n):
        L[i,:] = L[i,:] / A[i,i]
        R[i,:] = R[i,:] / A[i,i]
        b[i] /= A[i,i]
       
    # loop principal
    k = 0
    while k < MAX_ITER:
        x = -(L + R) @ x0 + b
        
        varepsilon = np.max(np.abs(x-x0)) / np.max( np.abs(x))
        print(f'Na iteração {k+1}, x=\n{x}, varepsilon={varepsilon}\n')
        
        if varepsilon < epsilon:
            break
        else:
            x0 = x
        k += 1
    
    # retorna x
    return x

def metodo_gauss_seidel(A,b,x0,epsilon,MAX_ITER):
    '''
    Resolver um sistema linear usando Gauss-Seidel.
    
    Entrada:
        A : matriz de coeficientes.
        b : vetor de termos independentes.
        x0 : valor inicial de x.
        epsilon : tolerância máxima.
        MAX_ITER : número máximo de iterações.
    Saída:
        x : vetor de incógnitas
    '''
    assert len(A.shape) == 2, 'Dever ser uma matriz (2D).'
    assert A.shape[0] == A.shape[1], 'Dever ser uma matriz quadrada.'
    
    # ordem do sistema
    n = A.shape[0]
    
    # decomposição de A
    L,D,R = decomp_A(A)
    
    # normalização de L, R, b
    for i in range(n):
        L[i,:] = L[i,:] / A[i,i]
        R[i,:] = R[i,:] / A[i,i]
        b[i] /= A[i,i]
       
    # loop principal
    k = 0
    while k < MAX_ITER:
        x = -(L + R) @ x0 + b
        
        varepsilon = np.max(np.abs(x-x0)) / np.max( np.abs(x))
        print(f'Na iteração {k+1}, x=\n{x}, varepsilon={varepsilon}\n')        
        
        if varepsilon < epsilon:
            break
        else:
            x0 = x
        k += 1
    
    # retorna x
    return x

# Método de Jacobi-Richardson

In [49]:
# entra com sistema linear
#A = np.array( [ [10., 1., -3.], [2., 10., 8.], [7., 1., 10.] ] )
#print(f'A minha matriz A é\n {A}\n')
#print(f'O formato de A é\n {A.shape}\n')
#b = np.array( [ [5.], [10.], [15.] ] )
#print(f'A meu vetor b é\n {b}\n')
#print(f'O formato de b é\n {b.shape}\n')
A = np.array( [ [10., 1., -1.], [1., 10., 1.], [2., -1., 10.] ] )
print(f'A minha matriz A é\n {A}\n')
print(f'O formato de A é\n {A.shape}\n')
b = np.array( [ [10.], [12.], [11.] ] )
print(f'A meu vetor b é\n {b}\n')
print(f'O formato de b é\n {b.shape}\n')

A minha matriz A é
 [[10.  1. -1.]
 [ 1. 10.  1.]
 [ 2. -1. 10.]]

O formato de A é
 (3, 3)

A meu vetor b é
 [[10.]
 [12.]
 [11.]]

O formato de b é
 (3, 1)



In [50]:
# resolve o sistema linear
epsilon = 0.1
MAX_ITER = 20
x0 = np.array( [[0.0],[0.0],[0.0]] )
x = metodo_jacobi_richardson(A,b,x0,epsilon,MAX_ITER)
print(f'O valor de x é \n{x}\n')

Na iteração 1, x=
[[1. ]
 [1.2]
 [1.1]], varepsilon=1.0

Na iteração 2, x=
[[0.99]
 [0.99]
 [1.02]], varepsilon=0.20588235294117643

Na iteração 3, x=
[[1.003]
 [0.999]
 [1.001]], varepsilon=0.018943170488534302

O valor de x é 
[[1.003]
 [0.999]
 [1.001]]



# Método de Gauss-Seidel

In [51]:
# entra com sistema linear
A = np.array( [ [4., -1., -1.], [2., -5., 1.], [1., 2., 4.] ] )
print(f'A minha matriz A é\n {A}\n')
print(f'O formato de A é\n {A.shape}\n')
b = np.array( [ [-7.], [-5.], [4.] ] )
print(f'A meu vetor b é\n {b}\n')
print(f'O formato de b é\n {b.shape}\n')

A minha matriz A é
 [[ 4. -1. -1.]
 [ 2. -5.  1.]
 [ 1.  2.  4.]]

O formato de A é
 (3, 3)

A meu vetor b é
 [[-7.]
 [-5.]
 [ 4.]]

O formato de b é
 (3, 1)



In [52]:
# resolve o sistema linear
epsilon = 0.1
MAX_ITER = 20
x0 = np.array( [[0.0],[0.0],[0.0]] )
x = metodo_gauss_seidel(A,b,x0,epsilon,MAX_ITER)
print(f'O valor de x é \n{x}\n')

Na iteração 1, x=
[[-1.75]
 [ 1.  ]
 [ 1.  ]], varepsilon=1.0

Na iteração 2, x=
[[-1.25  ]
 [ 0.5   ]
 [ 0.9375]], varepsilon=0.4

Na iteração 3, x=
[[-1.390625]
 [ 0.6875  ]
 [ 1.0625  ]], varepsilon=0.1348314606741573

Na iteração 4, x=
[[-1.3125    ]
 [ 0.65625   ]
 [ 1.00390625]], varepsilon=0.05952380952380952

O valor de x é 
[[-1.3125    ]
 [ 0.65625   ]
 [ 1.00390625]]

