In [1]:
import numpy as np
from scipy import linalg

# Funçoes para a solução de sistemas lineares

In [15]:
def decomp_A(A):
    L = np.tril(A, k=-1)
    D = np.diag(np.diag(A))
    R = np.triu(A, k=1)
    return L, D, R

def jacobi_richardson(A,b):
    L,D,R = decomp_A

In [3]:
A = np.array( [ [2., -3., 1.], [4., -6., -1.], [1., 2., 1.] ] )
print(f'A minha matriz A é\n {A}\n')
print(f'O formato de A é\n {A.shape}\n')
b = np.array( [ [-5.], [-7.], [4.] ] )
print(f'A meu vetor b é\n {b}\n')
print(f'O formato de b é\n {b.shape}\n')

A minha matriz A é
 [[ 2. -3.  1.]
 [ 4. -6. -1.]
 [ 1.  2.  1.]]

O formato de A é
 (3, 3)

A meu vetor b é
 [[-5.]
 [-7.]
 [ 4.]]

O formato de b é
 (3, 1)



In [17]:
L,D,R = jacobi_richardson(A,b)
print(L)
print(D)
print(R)
print(A)
print(L+D+R)

[[0. 0. 0.]
 [4. 0. 0.]
 [1. 2. 0.]]
[[ 2.  0.  0.]
 [ 0. -6.  0.]
 [ 0.  0.  1.]]
[[ 0. -3.  1.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]
[[ 2. -3.  1.]
 [ 4. -6. -1.]
 [ 1.  2.  1.]]
[[ 2. -3.  1.]
 [ 4. -6. -1.]
 [ 1.  2.  1.]]
