In [1]:
import numpy as np
from scipy import linalg

# Funçoes para a solução de sistemas lineares

In [11]:
def decomp_A(A):
    '''
    Decomposição A nas matrizes triangulares e diagonais.
    
    Entrada:
        A : matriz de coeficientes.
    Saída:
        L : matriz triangular inferior.
        D : matriz diagonal.
        R : matriz triangular superior.
    '''
    L = np.tril(A, k=-1)
    D = np.diag(np.diag(A))
    R = np.triu(A, k=1)
    return L, D, R

def metodo_jacobi_richardson(A,b,x0,epsilon,MAX_ITER):
    '''
    Resolver um sistema linear usando Jocobi-Richardson.
    
    Entrada:
        A : matriz de coeficientes.
        b : vetor de termos independentes.
        x0 : valor inicial de x.
        epsilon : tolerância máxima.
        MAX_ITER : número máximo de iterações.
    Saída:
        x : vetor de incógnitas
    '''
    assert len(A.shape) == 2, 'Dever ser uma matriz (2D).'
    assert A.shape[0] == A.shape[1], 'Dever ser uma matriz quadrada.'
    
    # ordem do sistema
    n = A.shape[0]
    
    # decomposição de A
    L,D,R = decomp_A(A)
    
    # normalização de L, R, b
    for i in range(n):
        L[i,:] = L[i,:] / A[i,i]
        R[i,:] = R[i,:] / A[i,i]
        b[i] /= A[i,i]
       
    # loop principal
    k = 0
    while k < MAX_ITER:
        x = -(L + R) @ x0 + b
        
        print(f'Na iteração {k+1}, x=\n{x}\n')
        varepsilon = np.max(np.abs(x-x0)) / np.max( np.abs(x))
        
        if varepsilon < epsilon:
            break
        else:
            x0 = x
        k += 1
    
    # retorna x
    return x

def metodo_gauss_seidel(A,b,x0,epsilon,MAX_ITER):
    '''
    Resolver um sistema linear usando Gauss-Seidel.
    
    Entrada:
        A : matriz de coeficientes.
        b : vetor de termos independentes.
        x0 : valor inicial de x.
        epsilon : tolerância máxima.
        MAX_ITER : número máximo de iterações.
    Saída:
        x : vetor de incógnitas
    '''
    assert len(A.shape) == 2, 'Dever ser uma matriz (2D).'
    assert A.shape[0] == A.shape[1], 'Dever ser uma matriz quadrada.'
    
    # ordem do sistema
    n = A.shape[0]
    
    # decomposição de A
    L,D,R = decomp_A(A)
    
    # normalização de L, R, b
    for i in range(n):
        L[i,:] = L[i,:] / A[i,i]
        R[i,:] = R[i,:] / A[i,i]
        b[i] /= A[i,i]
       
    # loop principal
    k = 0
    while k < MAX_ITER:
        x = -(L + R) @ x0 + b
        
        print(f'Na iteração {k+1}, x=\n{x}\n')
        varepsilon = np.max(np.abs(x-x0)) / np.max( np.abs(x))
        
        if varepsilon < epsilon:
            break
        else:
            x0 = x
        k += 1
    
    # retorna x
    return x

In [13]:
A = np.array( [ [10., 2., 1.], [1., 5., 1.], [2., 3., 10.] ] )
print(f'A minha matriz A é\n {A}\n')
print(f'O formato de A é\n {A.shape}\n')
b = np.array( [ [7.], [-8.], [6.] ] )
print(f'A meu vetor b é\n {b}\n')
print(f'O formato de b é\n {b.shape}\n')

A minha matriz A é
 [[10.  2.  1.]
 [ 1.  5.  1.]
 [ 2.  3. 10.]]

O formato de A é
 (3, 3)

A meu vetor b é
 [[ 7.]
 [-8.]
 [ 6.]]

O formato de b é
 (3, 1)



In [14]:
epsilon = 0.01
MAX_ITER = 20
x0 = np.array( [[0.7],[-1.6],[0.6]] )
x = metodo_jacobi_richardson(A,b,x0,epsilon,MAX_ITER)
print(f'O valor de x é \n{x}\n')

Na iteração 1, x=
[[ 0.96]
 [-1.86]
 [ 0.94]]

Na iteração 2, x=
[[ 0.978]
 [-1.98 ]
 [ 0.966]]

Na iteração 3, x=
[[ 0.9994]
 [-1.9888]
 [ 0.9984]]

Na iteração 4, x=
[[ 0.99792]
 [-1.99956]
 [ 0.99676]]

O valor de x é 
[[ 0.99792]
 [-1.99956]
 [ 0.99676]]

